//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaryaAutomation.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public int Id { get; set; }
        public string Full_Name { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
    }
}
